function phi = build_system_embedding(A,B,adj)
    deg = sum(adj,2);
    avgDeg = mean(deg);
    maxDeg = max(deg);

    rhoA = max(abs(eig(A)));

    phi = [ ...
        size(A,1), size(B,2), ...
        avgDeg, maxDeg, ...
        rhoA, ...
        norm(A,'fro'), norm(B,'fro') ...
    ]';
    phi = phi / (norm(phi) + 1e-9);
end
